Cargo.lock
Cargo.toml
decoders/system-program-decoder/Cargo.toml
decoders/system-program-decoder/src/instructions/allocate.rs
decoders/system-program-decoder/src/instructions/allocate_with_seed.rs
decoders/system-program-decoder/src/instructions/assign_with_seed.rs
decoders/system-program-decoder/src/instructions/transfer_with_seed.rs

- allocate_with_seed
- allocate
- assign_with_seed
- transfer_with_seed

fix: make system program instruction data fields public

---

decoders/raydium-amm-v4-decoder/src/instructions/swap_base_in.rs
decoders/raydium-amm-v4-decoder/src/instructions/swap_base_out.rs

fix: change types for ArrangeAccounts impl

---

decoders/raydium-amm-v4-decoder/src/instructions/swap_base_in.rs
decoders/raydium-amm-v4-decoder/src/instructions/swap_base_out.rs

fix: hotfix of raydium amm accounts parse

---

decoders/token-program-decoder/src/instructions/transfer_checked.rs

fix: include mint account to transfer checked

---

Cargo.lock
Cargo.toml
README.md
decoders/okx-dex-decoder/Cargo.toml
decoders/okx-dex-decoder/README.md
decoders/okx-dex-decoder/src/accounts/mod.rs
decoders/okx-dex-decoder/src/instructions/commission_sol_from_swap.rs
decoders/okx-dex-decoder/src/instructions/commission_sol_proxy_swap.rs
decoders/okx-dex-decoder/src/instructions/commission_sol_swap.rs
decoders/okx-dex-decoder/src/instructions/commission_sol_swap2.rs
decoders/okx-dex-decoder/src/instructions/commission_spl_from_swap.rs
decoders/okx-dex-decoder/src/instructions/commission_spl_proxy_swap.rs
decoders/okx-dex-decoder/src/instructions/commission_spl_swap.rs
decoders/okx-dex-decoder/src/instructions/commission_spl_swap2.rs
decoders/okx-dex-decoder/src/instructions/from_swap_log.rs
decoders/okx-dex-decoder/src/instructions/mod.rs
decoders/okx-dex-decoder/src/instructions/proxy_swap.rs
decoders/okx-dex-decoder/src/instructions/swap.rs
decoders/okx-dex-decoder/src/instructions/swap2.rs
decoders/okx-dex-decoder/src/instructions/swap_event.rs
decoders/okx-dex-decoder/src/lib.rs
decoders/okx-dex-decoder/src/types/adaptor_id.rs
decoders/okx-dex-decoder/src/types/bridge_to_args.rs
decoders/okx-dex-decoder/src/types/commission_swap_args.rs
decoders/okx-dex-decoder/src/types/dex.rs
decoders/okx-dex-decoder/src/types/mod.rs
decoders/okx-dex-decoder/src/types/route.rs
decoders/okx-dex-decoder/src/types/swap_args.rs
decoders/okx-dex-decoder/src/types/swap_event.rs
decoders/okx-dex-decoder/src/types/swap_type.rs

feat: add OKX DEX Decoder

---

crates/core/src/datasource.rs
crates/core/src/transaction.rs
datasources/helius-atlas-ws-datasource/src/lib.rs
datasources/rpc-block-subscribe-datasource/src/lib.rs
datasources/rpc-transaction-crawler-datasource/src/lib.rs
datasources/yellowstone-grpc-datasource/src/lib.rs

https://github.com/sevenlabs-hq/carbon/issues/180

feat: Add block_time to TransactionUpdate and TransactionMetadata

---

crates/core/src/pipeline.rs

feat: add datasource cancellation token to pipeline

---

crates/cli/src/handlers/codama/parse_codama.rs
crates/cli/src/handlers/parse.rs
crates/cli/src/types.rs

- Also add missing import that i missed before

fix: Remove unused import for serde_big_array

---

datasources/rpc-transaction-crawler-datasource/src/lib.rs

Closes https://github.com/sevenlabs-hq/carbon/issues/246

RPC Transaction Crawler: Enable Discovering Newly Sent Transactions

---

crates/core/src/instruction.rs
crates/core/src/transformers.rs
crates/core/tests/README.md
crates/core/tests/fixtures/nested_cpi_tx.json

fix: 3rd depth level of calls

---

Cargo.lock
Cargo.toml
datasources/jito-shredstream-grpc-datasource/Cargo.toml
datasources/jito-shredstream-grpc-datasource/README.md
datasources/jito-shredstream-grpc-datasource/src/lib.rs

Based on the new deshred GRPC officially released by Jito
https://docs.jito.wtf/lowlatencytxnfeed/

feat: jito shredstream grpc datasource

---

crates/core/src/instruction.rs

close https://github.com/sevenlabs-hq/carbon/issues/213

feat: add `Serialize` for `DecodedInstruction`

---

Cargo.lock
crates/core/Cargo.toml
crates/core/src/instruction.rs
crates/core/src/pipeline.rs
decoders/jupiter-swap-decoder/src/types/swap.rs
examples/jupiter-swap-alerts/Cargo.toml
examples/jupiter-swap-alerts/README.md
examples/jupiter-swap-alerts/src/main.rs

fix:jupiter nested empty instructions

---

datasources/helius-atlas-ws-datasource/src/lib.rs

https://github.com/sevenlabs-hq/carbon/issues/269

fix: Duplicate webSocket connection

---

Cargo.lock
README.md
crates/core/src/account.rs
crates/core/src/account_deletion.rs
crates/core/src/datasource.rs
crates/core/src/error.rs
crates/core/src/instruction.rs
crates/core/src/lib.rs
crates/core/src/pipeline.rs
crates/core/src/processor.rs
crates/core/src/transformers.rs
crates/macros/src/schemas.rs
crates/macros/src/try_decode_ixs.rs
crates/proc-macros/src/lib.rs

tests: fix all doc tests

---

crates/core/src/instruction.rs

feat: Implement `IntoIter` Trait For `NestedInstructions`

---

crates/proc-macros/src/lib.rs

Closes https://github.com/sevenlabs-hq/carbon/issues/287

feat: lenient deserialize and warn about remaining bytes

---

crates/core/src/instruction.rs
crates/core/src/transformers.rs

With absolute path we can more easily find corresponding program logs.

feat: add InstructionMeta absolute_path

---

Cargo.toml
README.md
decoders/meteora-damm-v2-decoder/src/accounts/mod.rs
decoders/meteora-damm-v2-decoder/src/instructions/mod.rs
decoders/meteora-damm-v2-decoder/src/lib.rs
scripts/publish-crate.sh

fix: add PROGRAM_ID to meteora damm v2

---

crates/cli/templates/project.askama
datasources/rpc-transaction-crawler-datasource/src/lib.rs
examples/meteora-activities/src/main.rs

1. Allow users to specify their TX retry strategy.
2. Include a backoff and logs

Add Retries to the TX Crawler

---

decoders/raydium-cpmm-decoder/src/accounts/pool_state.rs

cf. https://github.com/raydium-io/raydium-cp-swap/blob/91a035ae0396412a91db6e7d121293156db7cbae/programs/cp-swap/src/states/pool.rs#L76-L78

fix: update Raydium CPMM PoolState account

---

datasources/rpc-transaction-crawler-datasource/src/lib.rs

Closes https://github.com/sevenlabs-hq/carbon/issues/368 by fixing a regression introduced in https://github.com/sevenlabs-hq/carbon/commit/8b2002afbea8d7a7c1183f7ff1266dbcd876d243.
Without this the rpc transaction crawler is unable to discover transactions that have been sent to a program after the initial `rpc_client.get_signatures_for_address_with_config` is called, and the only way to discover newly sent transactions is to repeatedly tear down the entire processing pipeline and recreate it which is not that great, and vastly impedes the abiltiy to index transactions in a timely manner.

Fix Rpc Transaction Crawler And Newly Sent Transactions

---

decoders/pump-swap-decoder/src/accounts/global_config.rs
decoders/pump-swap-decoder/src/types/global_config.rs

cf. https://solscan.io/account/ADyA8hdefvWN2dbGGWFotbzWxrAvLW83WG6QCVXvJKqw#anchorData

Update pumpswap globalconfig

---

decoders/token-2022-decoder/src/instructions/initialize_mint_pausable.rs
decoders/token-2022-decoder/src/instructions/initialize_scaled_ui_amount.rs
decoders/token-2022-decoder/src/instructions/mod.rs
decoders/token-2022-decoder/src/instructions/toggle_mint_pause.rs
decoders/token-2022-decoder/src/instructions/update_multiplier_scaled_ui_amount.rs

Adding Scale UI amount and Pausable Extension instruction for Token2022

---

decoders/system-program-decoder/src/accounts/legacy.rs
decoders/system-program-decoder/src/accounts/mod.rs

https://github.com/sevenlabs-hq/carbon/issues/400

feat: add Legacy account support in system program decoder

---

Cargo.lock
Cargo.toml
README.md
decoders/vertigo-decoder/Cargo.toml
decoders/vertigo-decoder/src/accounts/mod.rs
decoders/vertigo-decoder/src/accounts/pool.rs
decoders/vertigo-decoder/src/instructions/buy.rs
decoders/vertigo-decoder/src/instructions/buy_event.rs
decoders/vertigo-decoder/src/instructions/claim.rs
decoders/vertigo-decoder/src/instructions/create.rs
decoders/vertigo-decoder/src/instructions/mod.rs
decoders/vertigo-decoder/src/instructions/pool_created_event.rs
decoders/vertigo-decoder/src/instructions/quote_buy.rs
decoders/vertigo-decoder/src/instructions/quote_sell.rs
decoders/vertigo-decoder/src/instructions/sell.rs
decoders/vertigo-decoder/src/instructions/sell_event.rs
decoders/vertigo-decoder/src/lib.rs
decoders/vertigo-decoder/src/types/buy_event.rs
decoders/vertigo-decoder/src/types/create_params.rs
decoders/vertigo-decoder/src/types/fee_params.rs
decoders/vertigo-decoder/src/types/mod.rs
decoders/vertigo-decoder/src/types/pool.rs
decoders/vertigo-decoder/src/types/pool_created.rs
decoders/vertigo-decoder/src/types/sell_event.rs
decoders/vertigo-decoder/src/types/swap_params.rs
decoders/vertigo-decoder/src/types/swap_result.rs
scripts/publish-crate.sh

This PR implements a decoder for Vertigo DEX: https://www.vertigo.sh/
The IDL is taken from solscan: https://solscan.io/account/vrTGoBuy5rYSxAfV3jaRJWHH6nN9WK4NRExGxsk1bCJ#programIdl

feat: vertigo program decoder
